import { Lora, Work_Sans } from "next/font/google";
import "./globals.css";
import GridBackground from "./components/GridBackground";

// ✅ Load Google Fonts via next/font/google (no manual @import in CSS)
const lora = Lora({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

// ✅ Page metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${workSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
